# Exported from Render on 2025-12-10T10:07:54Z
version: "1"
services:
- type: web
  name: afropalsjobs-api
  runtime: python
  repo: https://github.com/ngwache41/Afro-Pals-Jobs
  plan: starter
  envVars:
  - key: SMTP_PASSWORD
    sync: false
  - key: SMTP_USERNAME
    sync: false
  - key: SMTP_PORT
    sync: false 
  - key: SMTP_HOST
    sync: false
  - key: R2_ENDPOINT
    sync: false
  - key: R2_BUCKET_NAME
    sync: false
  - key: R2_SECRET_ACCESS_KEY
    sync: false
  - key: R2_ACCESS_KEY_ID
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: MONGO_URI
    sync: false
  - key: DOMAIN
    sync: false
  region: frankfurt
  buildCommand: python -m pip install -r requirements.txt
  startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
  healthCheckPath: /health
  autoDeployTrigger: commit
